<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
$storeId = Mage::app()->getStore()->getId();
$summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)->load($_product->getId());
?>
<div class="rating-star">
    <?php
    $x = $summaryData['rating_summary'];
    $stars = 0;
    for ($i = 1; $i <= 5; $i++) {
        if ((($i - 1) * 20 < $x) && ($x <= $i * 20)) {
            $stars = $i;
        }
    }
    ?>
    <?php for ($i = 0; $i < $stars; $i++): ?>
        <i class="icon-star active"></i>
    <?php endfor; ?>
    <?php for ($i = 0; $i < 5-$stars; $i++): ?>
        <i class="icon-star"></i>
    <?php endfor; ?>
</div>