<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxcartpro
 * @version    3.2.10
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="modal-ajax">
    <?php $_product = $this->getProduct() ?>
    <script type="text/javascript">
        optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
        optionsPrice.productType = '<?php echo $_product->getTypeId() ?>';
        if (typeof(Enterprise) != 'undefined' && typeof(Enterprise.Bundle) != 'undefined') {
            (function(){
                var oldFn = Enterprise.Bundle.swapReloadPrice;
                Enterprise.Bundle.swapReloadPrice = function() {
                    if (Enterprise.Bundle.isSwaped === true) {
                        return;
                    }
                    oldFn();
                    Enterprise.Bundle.isSwaped = true;
                }
            })();
        }
        if (optionsPrice.productType == "bundle") {
            var taxCalcMethod = undefined;
            var CACL_UNIT_BASE = undefined;
            var CACL_ROW_BASE = undefined;
            var CACL_TOTAL_BASE = undefined;
        }
    </script>
    <form action="<?php echo Mage::helper('ajaxcartpro/catalog')->getSubmitUrl($this, $_product) ?>" method="post" id="product-addtocart-form-acp"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" value="<?php echo $_product->getId() ?>" name="product">
        <input type="hidden" value="1" name="awacp-options-form">
        <div id="bundle-product-wrapper">
            <div id="acp-product-options" class="modal animated zoomIn hinge-05 modal-ajax-cart">
                <div class="modal-dialog product-options" id="product-options-wrapper">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close aw-acp-continue"><i class="icon-close"></i></button>
                            <h4 class="modal-title product-name"><?php echo $_product->getName() ?></h4>
                        </div>
                        <div class="modal-body">
                            <ul class="acp-msg-block ajaxcartpro-box-hide"></ul>
                            <div id="acp-product-type-data" class="hidden">
                                <?php echo $this->getChildHtml('product_type_data') ?>
                            </div>
                            <?php echo str_replace('var ', '', $this->getChildHtml('product_options'));?>
                            <?php echo $this->getChildHtml('product_configurable_options');?>
                            <?php echo $this->getChildHtml('product_downloadable_options');?>
                            <?php echo $this->getChildHtml('product_bundle_options');?>
                            <?php echo $this->getChildHtml('product_price');?>
                            <div class="add-to-cart">
                                <?php if(!$_product->isGrouped()): ?>
                                    <label for="qty"><?php echo $this->__('Qty:') ?></label>
                                    <div class="qty-group">
                                        <span class="qty-group-addon"><a href="#qty" class="button-qty qty-minus" data-value="-1" data-target="#qty-option" data-toggle="spinner"><span></span></a></span>
                                        <input data-ride="spinner" data-min="<?php echo min($this->getProductDefaultQty() * 1, 1)?>" type="text" name="qty" id="qty-option" maxlength="12" value="<?php echo max($this->getProductDefaultQty() * 1, 1)?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty">
                                        <span class="qty-group-addon"><a href="#qty" class="button-qty qty-plus" data-value="1" data-target="#qty-option" data-toggle="spinner"><span></span></a></span>
                                    </div>
                                <?php endif; ?>
                                <button type="button" class="button btn-cart aw-acp-checkout"><?php echo $this->__('Add to cart')?></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            if (typeof(Enterprise) != 'undefined' && typeof(Enterprise.Bundle) != 'undefined') {
                $H(optionsPrice.containers).each(function(pair){
                    if (!$(pair.value) && $(pair.value + optionsPrice.duplicateIdSuffix)) {
                        $(pair.value + optionsPrice.duplicateIdSuffix).setAttribute('id', pair.value);
                    }
                });
            }
        </script>
    </form>
    <script type="text/javascript">
        decorateGeneric($$('#product-options-wrapper dl'), ['last']);
        var productAddToCartFormAcp = new VarienForm('product-addtocart-form-acp');
        var validateDownloadableCallback = function (elmId, result) {
            var container = $('downloadable-links-list');
            if (result == 'failed') {
                container.removeClassName('validation-passed');
                container.addClassName('validation-failed');
            } else {
                container.removeClassName('validation-failed');
                container.addClassName('validation-passed');
            }
        };

        var validateOptionsCallback = function(elmId, result) {
            var container = $(elmId).up('ul.options-list');
            if (result == 'failed') {
                container.removeClassName('validation-passed');
                container.addClassName('validation-failed');
            } else {
                container.removeClassName('validation-failed');
                container.addClassName('validation-passed');
            }
        };

    </script>
</div>
