<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <?php $_products->addAttributeToSelect('image'); ?>
    <div class="carousel new-product">
        <div class="container">
            <div class="owl-carousel">
                <?php $productRenderer = $this->getChild('product_renderer'); ?>
                <?php foreach($_products->getItems() as $_product): ?>
                    <?php $productRenderer->setProduct($_product); ?>
                    <?php echo $productRenderer->toHtml(); ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $('.new-product .owl-carousel').on(
                'initialized.owl.carousel resized.owl.carousel',
                function (e) {
                    checkOwlControls(e);
                }
            );
            $('.new-product .owl-carousel').owlCarousel({
                margin: 0,
                loop: true,
                nav: false,
                dots: false,
                responsive: {
                    0:{
                        items: 1
                    },
                    600:{
                        items: 2
                    },
                    960:{
                        items: 3
                    },
                    1200:{
                        items: 3
                    }
                }
            });
        });
    </script>
<?php endif; ?>
