<?php

/**
 * Unicode Systems
 * @category   Uni
 * @package    Uni_Banner
 * @copyright  Copyright (c) 2010-2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php

$bannerGroupCode = $this->getBannerGroupCode();
$data = $this->getDataByGroupCode($bannerGroupCode);
$bannerGroupData = $data['group_data'];
$template = '';
$masterslider = $bannerGroupData->getMasterslider();
if (count($bannerGroupData) > 0):
    $preEff = $bannerGroupData->getPreBannerEffects();
    $bannerType = $bannerGroupData->getAnimationType();
?>
<?php    
    if ($bannerType == 1):
        $template = $this->getLayout()->createBlock('banner/banner', 'custom.banner')
            ->setBannerGroupCode($bannerGroupCode)->addData($this->getData())
            ->setTemplate('unibanner/effects/custom.phtml')->toHtml();
    elseif ($masterslider):
        $template = $this->getLayout()->createBlock('banner/banner', 'eco.banner')
            ->setBannerGroupCode($bannerGroupCode)->addData($this->getData())
            ->setTemplate('unibanner/effects/eco_masterslider.phtml')->toHtml();
    else:
        switch ($preEff) {
            case 'slide':
            case 'fade' :
                $template = $this->getLayout()->createBlock('banner/banner', 'eco.banner')
                    ->setBannerGroupCode($bannerGroupCode)->addData($this->getData())
                    ->setTemplate('unibanner/effects/eco.phtml')->toHtml();
            break;
            case 'Image Slide Show':
                $template = $this->getLayout()->createBlock('banner/banner', 'slideshow.banner')
                    ->setBannerGroupCode($bannerGroupCode)->addData($this->getData())
                    ->setTemplate('unibanner/effects/slideshow.phtml')->toHtml();
            break;
            case 'Square Transition Banner':
                $template = $this->getLayout()->createBlock('banner/banner', 'strans.banner')
                    ->setBannerGroupCode($bannerGroupCode)->addData($this->getData())
                    ->setTemplate('unibanner/effects/strans.phtml')->toHtml();
            break;
            case 'Text Fade Banner':
                $template = $this->getLayout()->createBlock('banner/banner', 'textfade.banner')
                    ->setBannerGroupCode($bannerGroupCode)->addData($this->getData())
                    ->setTemplate('unibanner/effects/textfade.phtml')->toHtml();
            break;
            case 'Play And Pause Slide Show':
                $template = $this->getLayout()->createBlock('banner/banner', 'playpause.banner')
                    ->setBannerGroupCode($bannerGroupCode)->addData($this->getData())
                    ->setTemplate('unibanner/effects/playpause.phtml')->toHtml();
            break;
            case 'Numbered Banner':
                $template = $this->getLayout()->createBlock('banner/banner', 'numbered.banner')
                    ->setBannerGroupCode($bannerGroupCode)->addData($this->getData())
                    ->setTemplate('unibanner/effects/numbered.phtml')->toHtml();
            break;
            case 'image spring slider':
                $template = $this->getLayout()->createBlock('banner/banner', 'springslider.banner')
                    ->setBannerGroupCode($bannerGroupCode)->addData($this->getData())
                    ->setTemplate('unibanner/effects/springslider.phtml')->toHtml();
            break;
            case 'image vertical slider':
                $template = $this->getLayout()->createBlock('banner/banner', 'verslider.banner')
                    ->setBannerGroupCode($bannerGroupCode)->addData($this->getData())
                    ->setTemplate('unibanner/effects/verslider.phtml')->toHtml();
            break;
            case 'image glider':
                $template = $this->getLayout()->createBlock('banner/banner', 'glider.banner')
                    ->setBannerGroupCode($bannerGroupCode)->addData($this->getData())
                    ->setTemplate('unibanner/effects/horslider.phtml')->toHtml();
            break;
        }
    endif;
    echo $template;
endif;
?>