<?php
/**
 *
 * Copyright (c) 2015 Ecomitize Ltd
 *
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$_category = Mage::getSingleton('catalog/layer')->getCurrentCategory();
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$productRenderer = $this->getChild('product_renderer');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="category-products"><p><?php echo $this->__('There are no products matching the selection.') ?></p></div>
<?php else: ?>
    <div class="category-products">
        <?php echo $this->getChildHtml('product_list_state_layer'); ?>
        <?php echo $this->getToolbarHtml(); ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <div class="category-row products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <?php $productRenderer->setProduct($_product); ?>
                    <div class="category-item">
                        <?php echo $productRenderer->toHtml(); ?>
                    </div>
                <?php endforeach ?>
            </div>
        <?php else: ?>
            <div class="category-row products-grid">
                <?php foreach ($_productCollection as $_product): ?>
                    <?php $productRenderer->setProduct($_product); ?>
                    <div class="category-item">
                        <?php echo $productRenderer->toHtml(); ?>
                    </div>
                <?php endforeach ?>
            </div>
        <?php endif; ?>
        <div class="toolbar-footer">
            <?php echo $this->getToolbarHtml(); ?>
        </div>
    </div>
<?php endif; ?>

<?php if (!Mage::getStoreConfig('ecomitize_all_scroll_options/messages/scroll_option')): ?>
    <script>
        if ( typeof ias != 'undefined' && ias != false && ias != null ) {

            var isHasIASTriggerExtension = false;
            for (var i = 0; i < ias.extensions.length; i++) {
                if ( ias.extensions[i] instanceof IASTriggerExtension ) {
                    isHasIASTriggerExtension = true;
                    break;
                }
            }
            if (!isHasIASTriggerExtension) {
                ias.extension(new IASTriggerExtension({
                    text: '<?php echo $this->__('Show More') ?>'
                }));
            }
        }
    </script>
<?php endif;?>
