<ul class="nav account-nav<?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?> user-active<?php else: ?> user-not-active<?php endif; ?>">
    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/compare/link.phtml')->toHtml(); ?>
    <li class="dropdown account-nav-dropdown">
        <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
            <a data-toggle="dropdown" href="<?php echo $this->getUrl('customer/account/login'); ?>"><span><?php echo $this->__('Log in / Sign up'); ?></span></a>
            <ul class="dropdown-menu pull-right dropdown-menu-account">
                <li>
                    <?php echo $this->getChildHtml('header_customer_form_mini_login'); ?>
                </li>
            </ul>
        <?php else: ?>
            <a data-toggle="dropdown" href="<?php echo $this->getUrl('customer/account'); ?>"><span><?php echo $this->__('My Account'); ?></span></a>
            <ul class="dropdown-menu pull-right dropdown-menu-account">
                <li><a href="<?php echo $this->getUrl('customer/account'); ?>"><?php echo $this->__('Account Dashboard') ?></a></li>
                <li><a href="<?php echo $this->getUrl('giftvoucher/index/index'); ?>"><?php echo $this->__('Gift Cart') ?></a></li>
                <li><a href="<?php echo $this->getUrl('customer/account/edit'); ?>"><?php echo $this->__('Account Information') ?></a></li>
                <li><a href="<?php echo $this->getUrl('customer/address/new'); ?>"><?php echo $this->__('Address Book') ?></a></li>
                <li><a href="<?php echo $this->getUrl('sales/order/history'); ?>"><?php echo $this->__('My Orders') ?></a></li>
                <li><a href="<?php echo $this->getUrl('review/customer'); ?>"><?php echo $this->__('My Product Reviews') ?></a></li>
                <?php echo $this->getLayout()->createBlock('wishlist/links')->setBlockName('wishlist_link')->toHtml(); ?>
                <li><a href="<?php echo $this->getUrl('newsletter/manage'); ?>"><?php echo $this->__('Newsletter Subscriptions') ?></a></li>
                <li><a href="<?php echo $this->getUrl('customer/account/logout'); ?>"><?php echo $this->__('Logout'); ?></a></li>
            </ul>
        <?php endif; ?>
    </li>
</ul>

