<?php
function  get_categories($categories, $storeId) {
    $array= '<ul class="level0 dropdown-menu">';
    foreach($categories as $category) {
        if($category->hasChildren()) {
            $drop = 'dropdown';
            $dropToggle = 'dropdown-toggle';
            $dropHover = ' data-hover="dropdown"';
        } else {
            $drop = '';
            $dropToggle = '';
            $dropHover = '';
        }
        $cat = Mage::getModel('catalog/category')->load($category->getId());
        $rewrite = Mage::getModel('core/url_rewrite')->load($category->getId())
        $altUrl = $rewrite->getTargetPath();
        $array .= '<li class="level'.$cat->getLevel().' '.$drop.'">'.
            '<a href="' .$altUrl. '" class="'.$dropToggle.'"'.$dropHover.'>' .$category->getName() . "</a>";
        if($category->hasChildren()) {
            $children = Mage::getModel('catalog/category')->getCategories($category->getId());
            $array .=  get_categories($children);
        }
        $array .= '</li>';
    }
    return  $array . '</ul>';
}
?>

<div class="navbar-nav-container">
    <div class="container">
        <nav id="navbar" class="navbar">
            <ul class="nav navbar-nav">
                <?php
                foreach (Mage::app()->getWebsites() as $website) {
                    foreach ($website->getGroups() as $group) {
                        $stores = $group->getStores();
                        foreach ($stores as $store) {
                            $storeId = $store->getId();
                            if ($storeId == 1) {} else {
                                $store_url   = Mage::app()->getStore($storeId)->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);
                                echo '<li class="dropdown-left level0 nav-1 level-top dropdown"><a href="'.$store['code'].'" class="level-top dropdown-toggle" data-hover="dropdown">'.$store->getName().'</a>';

                                $rootcatId= $store->getRootCategoryId();
                                $categories = Mage::getModel('catalog/category')->getCategories($rootcatId);

                                echo  get_categories($categories, $storeId);

                                /*$rootId = $store->getRootCategoryId();
                                $collection = Mage::getModel('catalog/category')
                                    ->getResourceCollection()
                                    ->addAttributeToSelect('*')
                                    ->addFieldToFilter('path', array('like' => "1/{$rootId}/%"))
                                    ->addIsActiveFilter()
                                    ->addUrlRewriteToResult();
                                foreach ($collection as $cat) {

                                    $categoryId  = $cat->getId();
                                    $catEntity   = Mage::getModel('catalog/category')->setStoreId($storeId)->load($categoryId);
                                    $caturlkey   = $catEntity->getUrlKey();
                                    $altUrl      = $store_url.$caturlkey;
                                    if ($catEntity->getChildren()) {
                                        echo '<li class="level'.$cat->getLevel().' nav-2 dropdown"><a href="'.$altUrl.'.html">'.$cat->getName().'</a>';
                                        echo '<ul class="level'.$cat->getLevel().' dropdown-menu">';
                                        $categories = Mage::getModel('catalog/category')->load($categoryId)->getChildren();
                                        $catArray = explode(',', $categories);
                                        foreach($catArray as $child)
                                        {
                                            $_child = Mage::getModel( 'catalog/category' )->load( $child );
                                            $objsub = $_child;
                                            $subId  = $objsub->getId();
                                            $subEntity   = Mage::getModel('catalog/category')->setStoreId($storeId)->load($subId);
                                            $suburlkey   = $subEntity->getUrlKey();
                                            $altSubUrl   = $altUrl.'/'.$suburlkey;
                                            echo '<li class="level'.$cat->getLevel().' nav-2 dropdown"><a href="'.$altSubUrl.'.html">'.$_child->getName().'</a></li>';
                                        }
                                        echo '</ul>';
                                        echo '</li>';
                                    } else {
                                        echo '<li class="level-'.$cat->getLevel().'"><a href="'.$altUrl.'">'.$cat->getName().'</a></li>';
                                    }
                                }*/
                                echo '</li>';
                            }
                        }
                    }
                }
                ?>
            </ul>
        </nav>
    </div>
</div>