<div class="navbar-nav-container">
    <div class="container">
        <nav id="navbar" class="navbar">
            <ul class="nav navbar-nav">
                <?php
                foreach (Mage::app()->getWebsites() as $website) {
                    foreach ($website->getGroups() as $group) {
                        $stores = $group->getStores();
                        foreach ($stores as $store) {
                            if ($store->getId() == 1) {} else {
                                echo '<li class="dropdown-left level0 nav-1 first level-top dropdown"><a href="'.$store['code'].'">'.$store->getName().'</a></li>';
                                echo '<ul class="level0 dropdown-menu">';
                                $rootId = $store->getRootCategoryId();
                                $collection = Mage::getModel('catalog/category')
                                    ->getResourceCollection()
                                    ->addAttributeToSelect('*')
                                    ->addFieldToFilter('path', array('like' => "1/{$rootId}/%"))
                                    ->addIsActiveFilter();
                                foreach ($collection as $cat) {
                                    echo '<li><a href="'.$cat->getUrl().'">'.$cat->getName().'</a></li>';
                                }
                                echo '</ul>';
                            }
                        }
                    }
                }
                ?>
            </ul>
        </nav>
    </div>
</div>