<div class="navbar-nav-container">
    <div class="container">
        <nav id="navbar" class="navbar">
            <ul class="nav navbar-nav">
                <?php
                foreach (Mage::app()->getWebsites() as $website) {
                    foreach ($website->getGroups() as $group) {
                        $stores = $group->getStores();
                        foreach ($stores as $store) {
                            echo $store['code'];
                            /*if (!$store['code'] == 'sandbox') {
                                echo '<li><a href="'.$store['code'].'">'.$store->getName().'</a></li>';
                            }*/
                        }
                    }
                }
                ?>
            </ul>
        </nav>
    </div>
</div>