<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<div class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></div>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<?php echo $this->getMessagesBlock()->toHtml(); ?>
<div class="page-title category-title">
    <h1><?php echo $_category->getName() ?></h1>
</div>
<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div class="row-category-description">
        <?php if($_imgUrl): ?>
            <?php echo $_imgHtml; ?>
        <?php endif; ?>
        <div class="category-description">
            <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
        </div>
    </div>
<?php endif; ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>
<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
