<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Ecomitize Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php echo $this->getChildHtml('footer_scripts'); ?>
</div>
<footer>
    <div class="container">
        <div class="footer-row">
            <div class="footer-col footer-left">
                <nav class="footer-nav">
                    <?php echo $this->getChildHtml('footer-nav'); ?>
                </nav>
            </div>
            <div class="footer-col footer-right">
                <?php echo $this->getChildHtml('newsletter'); ?>
                <?php if(Mage::getStoreConfig('general/store_information/phone')): ?>
                    <div class="footer-phone">
                        <a href="tel:<?php echo Mage::getStoreConfig('general/store_information/phone'); ?>"><?php echo Mage::getStoreConfig('general/store_information/phone'); ?></a>
                    </div>
                <?php endif; ?>
                <?php if(Mage::getStoreConfig('general/store_information/address')): ?>
                    <address><?php echo Mage::getStoreConfig('general/store_information/address'); ?></address>
                <?php endif; ?>
            </div>
            <?php if (Mage::getStoreConfig('design/footer/copyright')): ?>
                <div class="footer-col footer-copyright"><?php echo $this->__(Mage::getStoreConfig('design/footer/copyright')) ?></div>
            <?php endif; ?>
        </div>
    </div>
</footer>
<button class="btn-scroll-top" data-spy="affix" data-offset-top="500"><i class="icon-arrow-up2"></i></button>
<script>(function($,d){$.each(readyQ,function(i,f){$(f)});$.each(bindReadyQ,function(i,f){$(d).bind("ready",f)})})(jQuery,document)</script>