<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Ecomitize Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
?>
<?php if($this->getCollection()->getSize()): ?>
    <?php if($this->getLastPageNum()>1): ?>
        <ul class="pagination">
            <li class="previous<?php echo $this->isFirstPage() ? ' first' : ''; ?>">
                <a href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo $this->__('Previous') ?>">
                    <?php if(!$this->getAnchorTextForPrevious()): ?>
                        <?php echo $this->__('Prev') ?>
                    <?php else: ?>
                        <?php echo $this->getAnchorTextForPrevious() ?>
                    <?php endif;?>
                </a>
            </li>
            <?php if ($this->canShowFirst()): ?>
                <li class="first"><a href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
            <?php endif;?>
            <?php if ($this->canShowPreviousJump()): ?>
                <li class="previous"><a title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
            <?php endif;?>
            <?php foreach ($this->getFramePages() as $_page): ?>
                <?php if ($this->isPageCurrent($_page)): ?>
                    <li class="active"><span><?php echo $_page ?></span></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
                <?php endif;?>
            <?php endforeach;?>
            <?php if ($this->canShowNextJump()): ?>
                <li><a href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
            <?php endif;?>
            <?php if ($this->canShowLast()): ?>
              <li class="last"><a href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
            <?php endif;?>
            <li class="next<?php echo $this->isLastPage() ? ' last' : ''; ?>">
                <a href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo $this->__('Next') ?>">
                    <?php if(!$this->getAnchorTextForNext()): ?>
                        <?php echo $this->__('Next') ?>
                    <?php else: ?>
                        <?php echo $this->getAnchorTextForNext() ?>
                    <?php endif;?>
                </a>
            </li>
        </ul>
    <?php endif; ?>
<?php endif ?>
