<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Ecomitize Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * Top menu for storeec
 *
 * @see Mage_Page_Block_Html_Topmenu
 */

?>

<?php $_menu = $this->getHtml('level-top') ?>
<?php if ($_menu): ?>
<div class="navbar-nav-container"<?php if ($this->getTopmenuPosition() == 'fixed'): ?> data-spy="affix" data-offset-top="<?php echo $this->getOffsetTop(); ?>"<?php endif; ?>>
    <div class="container">
        <nav id="navbar" class="navbar">
            <ul class="nav navbar-nav">
                <?php echo $_menu; ?>
            </ul>
        </nav>
    </div>
</div>
<?php endif ?>