

<?php
if ( !defined('BANNER_TYPE_IMAGE') ) {
    define('BANNER_TYPE_IMAGE',   0);
}
if ( !defined('BANNER_TYPE_CONTENT') ) {
    define('BANNER_TYPE_CONTENT', 1);
}
$gCode = $this->getBannerGroupCode();
$data  = $this->getDataByGroupCode($gCode);
$gData = $data['group_data'];
$mode  = $gData->getPreBannerEffects();
$countShowcase = 0;
?>
<?php if (count($data['banner_data'])): ?>
    <?php if ($gCode == 'showcase') : ?>
        <div class="masonri-grid">
            <?php if ($data['group_data']->getRandom()) {shuffle($data['banner_data']);} ?>
            <?php $counter = 0; ?>
            <?php foreach ($data['banner_data'] as $banner): ?>
                <?php if ( !is_null( $data['group_data']->getRandomCount() ) && $data['group_data']->getRandomCount() <= $counter ): ?>
                    <?php break; ?>
                <?php endif; ?>
                <?php $counter++ ?>
                <div class="masonri-item item-<?php echo $counter; ?> <?php if ($countShowcase == 1 || $countShowcase == 4 || $countShowcase == 6 || $countShowcase == 7):
                    echo('masonri-item--h2');
                elseif ($countShowcase == 2):
                    echo('masonri-item--h2 masonri-item--w2');
                endif; ?>">
                    <?php
                    $type = $banner->getBannerType();
                    $title = $banner->getTitle();
                    $link = $banner->getLink();
                    $imgName = $banner->getFilename();
                    ?>
                    <?php if ($type == BANNER_TYPE_IMAGE) :
                        $image = null;
                        $path = Mage::getBaseDir('media') . DS . $imgName;
                        if (@file_exists($path) && $size = getimagesize($path)) :
                            $image = ($size[0] > $this->getBannerImgMaxWidth() )
                                ? $this->getResizeImage($imgName, $gCode, $this->getBannerImgMaxWidth())
                                : Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $imgName;
                        endif;
                        if ($image) : ?>
                            <?php if ($link): ?>
                                <a class="masonri-item__img" href="<?php echo $link; ?>"
                                   style="background-image: url(<?php echo $image; ?>);"><span><?php echo $title; ?></span></a>
                            <?php else: ?>
                                <div class="masonri-item__img" style="background-image: url(<?php echo $image; ?>);">
                                    <span><?php echo $title; ?></span></div>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
                <?php $countShowcase++ ?>
            <?php endforeach; ?>
        </div>
        <script>
            jQuery(document).ready(function ($) {
                $('.masonri-grid').masonry({itemSelector: '.masonri-item', layoutComplete: masonry_refresh()});
                function masonry_refresh() {
                    $('.masonri-grid').addClass('visible');
                }
            })
        </script>
    <?php else: ?>
        <div class="banners banners-<?php echo $gCode ?>">

            <?php if ($data['group_data']->getSlider() && !((int)$data['group_data']->getRandomCount() == 1)): ?><div class="owl-carousel<?php if ($this->getBannerHeight() == 'true'): ?> owl-height<?php endif; ?>"><?php endif; ?>

                <?php if ($data['group_data']->getRandom()) {shuffle($data['banner_data']);} ?>
                <?php $counter = 0; ?>
                <?php foreach ($data['banner_data'] as $banner): ?>
                    <?php if ( !is_null( $data['group_data']->getRandomCount() ) && $data['group_data']->getRandomCount() <= $counter ): ?>
                        <?php break; ?>
                    <?php endif; ?>
                    <?php $counter++ ?>
                    <div class="item" id="item-banner-<?php echo $banner->getBannerId() ?>"<?php if ($banner->getBannerBackgroundColor()): ?> style="background-color: <?php echo $banner->getBannerBackgroundColor() ?>"<?php endif; ?>>
                        <?php
                        $type    = $banner->getBannerType();
                        $title   = $banner->getTitle();
                        $link    = $banner->getLink();
                        $imgName = $banner->getFilename();
                        ?>
                        <?php if ($type == BANNER_TYPE_IMAGE) :
                            $image = null;
                            $path = Mage::getBaseDir('media') . DS . $imgName;
                            if (@file_exists($path) && $size = getimagesize($path)) :
                                $image = ($size[0] > $this->getBannerImgMaxWidth())
                                    ? $this->getResizeImage($imgName, $gCode,  $this->getBannerImgMaxWidth())
                                    : Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $imgName;
                            endif;
                            if ($image) : ?>
                                <a <?php echo ($link) ? sprintf('href="%s"', $link) : ''; ?>
                                    <?php echo($title && $gData->getShowTitle() ? sprintf('title="%s"', $title) : ''); ?>
                                    <?php echo ($link) ? 'target="_blank"' : ''; ?> class="banners-link">
                                    <img src="<?php echo $image; ?>" alt="<?php echo $title; ?>">
                                    <?php if ($banner->getBannerContent() && $gData->getShowContent()): ?>
                                        <span class="banner-wrapper">
                                            <span>
                                                <span class="banner-title"><?php echo $banner->getTitle(); ?></span>
                                                <span class="banner-content"><?php echo $banner->getBannerContent(); ?></span>
                                                <span class="banner-button">
                                                    <?php if ($banner->getButtonText()): ?>
                                                        <span><?php echo $banner->getButtonText(); ?></span>
                                                    <?php else: ?>
                                                        <?php echo $this->__('Shop Now') ?>
                                                    <?php endif; ?>
                                                </span>
                                            </span>
                                        </span>
                                    <?php endif; ?>
                                </a>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
                <?php if ($data['group_data']->getSlider() && !((int)$data['group_data']->getRandomCount() == 1)): ?>
            </div>
            <script type="text/javascript">
                jQuery(document).ready(function ($) {
                    var owl = $('.banners.banners-<?php echo $gCode ?> .owl-carousel');
                    owl.owlCarousel({
                        <?php if ($data['group_data']->getAutoScroll()): ?>
                        autoplay: true,
                        autoplayHoverPause: true,
                        <?php if ($data['group_data']->getAutoScrollTimeout()): ?>
                        autoplayTimeout: <?php echo $data['group_data']->getAutoScrollTimeout() ?>,
                        <?php endif; ?>
                        <?php endif; ?>
                        margin: 0,
                        navText: false,
                        <?php if ($mode == 'fade') : ?>
                        animateOut: 'fadeOut',
                        <?php endif; ?>
                        <?php if ($this->getBannerHeight() == 'true'): ?>
                        autoHeight: true,
                        <?php endif; ?>
                        loop: <?php echo $this->getBannerLoop(); ?>,
                        nav: <?php echo $this->getBannerNav(); ?>,
                        dots: <?php echo $this->getBannerDots(); ?>,
                        items: <?php echo $this->getBannerCount(); ?>,
                        <?php if ($this->getBannerResponsive() == 'true'): ?>
                        responsive: {
                            0:{
                                items: <?php echo $this->getBannerCountResponsiveXs(); ?>
                            },
                            600:{
                                items: <?php echo $this->getBannerCountResponsiveSm(); ?>
                            },
                            960:{
                                items: <?php echo $this->getBannerCountResponsiveMd(); ?>
                            },
                            1200:{
                                items: <?php echo $this->getBannerCountResponsiveLg(); ?>
                            },
                            1500: {
                                items: <?php echo $this->getBannerCountResponsiveXlg(); ?>
                            }
                        }
                        <?php endif; ?>
                    });
                    <?php if ($data['group_data']->getActiveItem()): ?>
                    $('.banners.banners-home-tabs .owl-dots > .owl-dot.item-banner-<?php echo $data['group_data']->getActiveItem() ?>').trigger('click');
                    <?php endif; ?>
                });
            </script>
        <?php endif; ?>
        </div>
    <?php endif; ?>
<?php endif; ?>

