<?php
$gCode = $this->getBannerGroupCode();
$data  = $this->getDataByGroupCode($gCode);
$gData = $data['group_data'];
$mode  = $gData->getPreBannerEffects();
?>
<?php if(count($data['banner_data'])): ?>
    <div class="banners banners-<?php echo $gCode ?>">
        <?php if ($data['group_data']->getSlider()): ?><div class="master-slider" id="banners-<?php echo $gCode ?>"><?php endif; ?>
            <?php if ($data['group_data']->getRandom()) {shuffle($data['banner_data']);} ?>
            <?php $counter = 0; ?>
            <?php foreach ($data['banner_data'] as $banner): ?>
                <?php if ($this->getBannerRandomCount()): ?>
                    <?php $bannerRandomCount = $this->getBannerRandomCount() ?>
                <?php else: ?>
                    <?php if ($gData->getRandomCount() == 0): ?>
                        <?php $bannerRandomCount = 999 ?>
                    <?php else: ?>
                        <?php $bannerRandomCount = $gData->getRandomCount() ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if (!is_null($bannerRandomCount) && $bannerRandomCount <= $counter ): ?>
                    <?php break; ?>
                <?php endif; ?>
                <?php $counter++ ?>
                <?php
                    $type    = $banner->getBannerType();
                    $title   = $banner->getTitle();
                    $content = $banner->getBannerContent();
                    $link    = $banner->getLink();
                    $imgName = $banner->getFilename();
                    $buttonText = $banner->getButtonText();
                ?>
                <div id="item-banner-<?php echo $banner->getBannerId() ?>" class="ms-slide slide-<?php echo $counter ?><?php if ($type == 0):?> type-image<?php endif; ?>"<?php if ($banner->getBannerBackgroundColor()): ?> style="background-color: <?php echo $banner->getBannerBackgroundColor() ?>"<?php endif; ?>>
                    <?php if ($type == 0): ?>
                    <?php
                        $image = null;
                        $path = Mage::getBaseDir('media').DS.$imgName;
                        if (@file_exists($path) && $size = getimagesize($path)):
                            $image = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$imgName;
                        endif;
                    ?>
                    <?php if ($image): ?>
                        <a data-src="<?php echo $image; ?>" <?php echo ($link) ? sprintf('href="%s"', $link):''; ?>
                            <?php echo ($title && $gData->getShowTitle() ? sprintf('title="%s"', $title):''); ?>
                            <?php echo ($data['group_data']->getLinkTarget()) ? 'target="_blank"':''; ?>>
                            <img src="<?php echo $this->getSkinUrl('images/blank.gif'); ?>" alt="<?php echo $title; ?>" title="<?php echo $title; ?>">
                        </a>
                    <?php endif; ?>
                    <?php elseif ($type == 1) : ?>
                        <?php if ($gData->getShowTitle() || $gData->getShowContent()): ?>
                            <div class="ms-layer">
                                <?php if ($title): ?>
                                    <?php if ($gData->getShowTitle()): ?>
                                        <div class="banner-title"><?php echo $title ?></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($content): ?>
                                    <?php if ($gData->getShowContent()): ?>
                                        <div class="banner-content"><?php echo $content ?></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($buttonText): ?>
                                    <a class="button btn-banner" <?php echo ($link) ? sprintf('href="%s"', $link):''; ?>
                                        <?php echo ($title && $gData->getShowTitle() ? sprintf('title="%s"', $title):''); ?>
                                        <?php echo ($data['group_data']->getLinkTarget()) ? 'target="_blank"':''; ?>>
                                        <?php echo $buttonText; ?>
                                    </a>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                        <?php if ($image): ?>
                            <img data-src="<?php echo $image; ?>" src="<?php echo $this->getSkinUrl('images/blank.gif'); ?>" alt="<?php echo $title; ?>" title="<?php echo $title; ?>">
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
            <?php if ($data['group_data']->getSlider()): ?>
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function ($) {
                var slider = new MasterSlider();
                slider.setup('banners-<?php echo $gCode ?>' , {
                    width: 1024,
                    height: 500,
                    fullwidth: true,
                    centerControls: false,
                    speed: 18,
                    view: 'flow',
                    loop: false
                });
                slider.control('arrows');
                slider.control('bullets' ,{autohide: false});
            });
        </script>
    <?php endif; ?>
    </div>
<?php endif; ?>