<form class="header-login-form" action="<?php echo $this->getPostActionUrl(); ?>" method="post" id="header-login-form">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="input-box">
        <label for="mini-login"><?php echo $this->__('Email:') ?><em>*</em></label>
        <input type="text" name="login[username]" id="mini-login" class="input-text required-entry validate-email">
    </div>
    <div class="input-box">
        <label for="mini-password"><?php echo $this->__('Password:') ?><em>*</em></label>
        <input type="password" name="login[password]" id="mini-password" class="input-text required-entry validate-password">
    </div>
    <div class="actions">
        <button type="submit" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
        <a class="btn-forgot-password" href="<?php echo $this->getForgotPasswordUrl() ?>"><span><?php echo $this->__('Forgot Your Password?') ?></span></a>
        <a class="btn-create-account" href="#" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><?php echo $this->__('Create an Account') ?></span></a>
    </div>
    <?php echo $this->getChildHtml('form.additional.info'); ?>
</form>
<script type="text/javascript">var dataForm = new VarienForm('header-login-form', true);</script>