<?php if($this->getCollection()->getSize()): ?>
    <div class="toolbar">
        <div class="toolbar-inner">
            <div class="toolbar-pager">
                <div class="pager">
                    <div class="amount">
                        <?php if($this->getLastPageNum()>1): ?>
                            <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                        <?php else: ?>
                            <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                        <?php endif; ?>
                    </div>
                    <div class="limiter">
                        <label><?php echo $this->__('Show') ?></label>
                        <select onchange="setLocation(this.value)">
                            <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                                <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                                    <?php echo $_limit ?> <?php echo $this->__('per page') ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="sort-by">
                    <label><?php echo $this->__('Sort By') ?></label>
                    <select onchange="setLocation(this.value)">
                        <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                            <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                                <?php echo $this->__($_order) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <?php if($this->getCurrentDirection() == 'desc'): ?>
                        <a class="button button-asc" href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Ascending Direction')) ?>"><i class="icon-arrow-up2"></i></a>
                    <?php else: ?>
                        <a class="button button-desc" href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Descending Direction')) ?>"><i class="icon-arrow-down2"></i></a>
                    <?php endif; ?>
                </div>
                <?php if( $this->isExpanded() ): ?>
                    <div class="sorter">
                        <?php if( $this->isEnabledViewSwitcher() ): ?>
                            <p class="view-mode">
                                <?php $_modes = $this->getModes(); ?>
                                <?php if($_modes && count($_modes)>1): ?>
                                    <label><?php echo $this->__('View as') ?>:</label>
                                    <?php foreach ($this->getModes() as $_code=>$_label): ?>
                                        <?php if($this->isModeActive($_code)): ?>
                                            <span class="toolbar-button"><a title="<?php echo $_label ?>" class="button active <?php echo strtolower($_code); ?>"><i class="icon-<?php echo strtolower($_label) ?>"></i><span><?php echo $_label ?></span></a></span>
                                        <?php else: ?>
                                            <span class="toolbar-button"><a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="button <?php echo strtolower($_code); ?>"><i class="icon-<?php echo strtolower($_label) ?>"></i><span><?php echo $_label ?></span></a></span>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </p>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <div class="filter">
                    <button class="button btn-filter filter-toggle" data-toggle="collapse" data-target=".col-left.sidebar"><span><?php echo $this->__('Filter') ?></span></button>
                </div>
            </div>
        </div>
        <?php if($this->getCollection()->getSize()): ?>
            <?php if ($this->getPagerHtml()): ?>
                <div class="row-pagination">
                    <?php echo $this->getPagerHtml(); ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
<?php endif ?>
